#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
foamCleanTutorials
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Mesh in parallel
runApplication blockMesh
runApplication surfaceFeatures
runApplication decomposePar -noFields
runParallel snappyHexMesh -overwrite
runApplication reconstructPar -noFields

touch foam.foam
#------------------------------------------------------------------------------
